name: flutter_ui
description: UI for DartVstHost plugin
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.3
  dart_vst_graph:
    path: ../dart_vst_graph
  collection: ^1.18.0
flutter:
  uses-material-design: true