name: dart_tests
description: Integration tests for Dart VST host and graph
version: 0.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  path: ^1.8.0
  test: ^1.24.0
  dart_vst_graph:
    path: ../dart_vst_graph
  dart_vst_host:
    path: ../dart_vst_host
dev_dependencies:
  ffi: ^2.1.0