name: dart_vst3_bridge
description: FFI bridge for building VST3 plugins in pure Dart. Provides the interface between Dart audio processing code and the VST3 SDK C++ infrastructure.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0